### ISSUE TITLE
Kinect not detected

### ISSUE THREAD

**Issue by pranali3215** [OpenKinect/libfreenect#492]
Hi.
So, everything was working fine, everything is working alright.
But after I restarted my laptop, the code does not work.
After a little debugging, I realise that the Kinect is not getting detected.
I run the **lsusb** command, it does not show kinect in the list.
I connect the camera on a Windows laptop, it gets detected.
I am using a Ubuntu 14.04 laptop.

Wondering if anyone has gotten a similar kind of error before ?

Edit: I restarted the computer and it has started being detected again. However, is there a reason that it happened in the first place ?

**Comment by piedar** [comment]
If it doesn't show in `lsusb`, we must dig deeper into kernel diagnostics messages.  Run the command

    dmesg --human --follow

Keep a note of the last line, then plug and unplug the device.  Dump this in a log file somewhere.  The next time the problem happens, repeat those steps.  By comparing the difference in the logs, we may find a clue to the root cause.
