### ISSUE TITLE
tp_print is removed from Cython 

### ISSUE THREAD

**Issue by sameone100** [OpenKinect/libfreenect#664]

**Comment by sameone100** [comment]
On Python10 I was manage to install python wraper by adding #define tp_print tp_vectorcall in freenect.c file

**Comment by piedar** [comment]
The existing `freenect.c` is outdated so it's better to generate it locally using one of these methods.

- run `python setup.py build_ext -f`
- delete `wrappers/python/freenect.c` (as done in 8f5ba392ddcfb62df31c3d5342c0989cbad7233f) and try again
- use `cmake -DBUILD_PYTHON3=ON` rather than running `setup.py`
